// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TKCHJrdQan6mrfk4NmuaLYhzFx_G5AI',
    appId: '1:811791488279:web:248ed320159d0debd49352',
    messagingSenderId: '811791488279',
    projectId: 'vihwafoodie',
    authDomain: 'vihwafoodie.firebaseapp.com',
    storageBucket: 'vihwafoodie.appspot.com',
    measurementId: 'G-LMSRJT4128',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhN3WVl3e7msej1v8UKdk7UeVe9s6-tE4',
    appId: '1:811791488279:android:97aed2df57cf7fffd49352',
    messagingSenderId: '811791488279',
    projectId: 'vihwafoodie',
    storageBucket: 'vihwafoodie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4FVDZDY5nL0vG3Da3DfMnMl31RWr3gMA',
    appId: '1:811791488279:ios:b8b6fd027eb4bfffd49352',
    messagingSenderId: '811791488279',
    projectId: 'vihwafoodie',
    storageBucket: 'vihwafoodie.appspot.com',
    iosClientId: '811791488279-5d8ohdmf60qc5lm9g6srhsbsfaspeldk.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4FVDZDY5nL0vG3Da3DfMnMl31RWr3gMA',
    appId: '1:811791488279:ios:b8b6fd027eb4bfffd49352',
    messagingSenderId: '811791488279',
    projectId: 'vihwafoodie',
    storageBucket: 'vihwafoodie.appspot.com',
    iosClientId: '811791488279-5d8ohdmf60qc5lm9g6srhsbsfaspeldk.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenOrderingApp',
  );
}
